// Code generated by protoc-gen-go. DO NOT EDIT.
// source: assistant.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NLPSentenceRequest struct {
	Time                 string               `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Message              string               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PreviousContext      []*TokenizedSentence `protobuf:"bytes,3,rep,name=previousContext,proto3" json:"previousContext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *NLPSentenceRequest) Reset()         { *m = NLPSentenceRequest{} }
func (m *NLPSentenceRequest) String() string { return proto.CompactTextString(m) }
func (*NLPSentenceRequest) ProtoMessage()    {}
func (*NLPSentenceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_04466eecc6514430, []int{0}
}

func (m *NLPSentenceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NLPSentenceRequest.Unmarshal(m, b)
}
func (m *NLPSentenceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NLPSentenceRequest.Marshal(b, m, deterministic)
}
func (m *NLPSentenceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NLPSentenceRequest.Merge(m, src)
}
func (m *NLPSentenceRequest) XXX_Size() int {
	return xxx_messageInfo_NLPSentenceRequest.Size(m)
}
func (m *NLPSentenceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NLPSentenceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NLPSentenceRequest proto.InternalMessageInfo

func (m *NLPSentenceRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *NLPSentenceRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *NLPSentenceRequest) GetPreviousContext() []*TokenizedSentence {
	if m != nil {
		return m.PreviousContext
	}
	return nil
}

type TokenizedSentence struct {
	Word                 []string `protobuf:"bytes,1,rep,name=word,proto3" json:"word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenizedSentence) Reset()         { *m = TokenizedSentence{} }
func (m *TokenizedSentence) String() string { return proto.CompactTextString(m) }
func (*TokenizedSentence) ProtoMessage()    {}
func (*TokenizedSentence) Descriptor() ([]byte, []int) {
	return fileDescriptor_04466eecc6514430, []int{1}
}

func (m *TokenizedSentence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenizedSentence.Unmarshal(m, b)
}
func (m *TokenizedSentence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenizedSentence.Marshal(b, m, deterministic)
}
func (m *TokenizedSentence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenizedSentence.Merge(m, src)
}
func (m *TokenizedSentence) XXX_Size() int {
	return xxx_messageInfo_TokenizedSentence.Size(m)
}
func (m *TokenizedSentence) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenizedSentence.DiscardUnknown(m)
}

var xxx_messageInfo_TokenizedSentence proto.InternalMessageInfo

func (m *TokenizedSentence) GetWord() []string {
	if m != nil {
		return m.Word
	}
	return nil
}

type AssistantMessage struct {
	Sentence             string   `protobuf:"bytes,1,opt,name=sentence,proto3" json:"sentence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AssistantMessage) Reset()         { *m = AssistantMessage{} }
func (m *AssistantMessage) String() string { return proto.CompactTextString(m) }
func (*AssistantMessage) ProtoMessage()    {}
func (*AssistantMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_04466eecc6514430, []int{2}
}

func (m *AssistantMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AssistantMessage.Unmarshal(m, b)
}
func (m *AssistantMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AssistantMessage.Marshal(b, m, deterministic)
}
func (m *AssistantMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AssistantMessage.Merge(m, src)
}
func (m *AssistantMessage) XXX_Size() int {
	return xxx_messageInfo_AssistantMessage.Size(m)
}
func (m *AssistantMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_AssistantMessage.DiscardUnknown(m)
}

var xxx_messageInfo_AssistantMessage proto.InternalMessageInfo

func (m *AssistantMessage) GetSentence() string {
	if m != nil {
		return m.Sentence
	}
	return ""
}

type NLPSentenceResponse struct {
	Fact                 []byte   `protobuf:"bytes,1,opt,name=fact,proto3" json:"fact,omitempty"`
	Tokens               []string `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NLPSentenceResponse) Reset()         { *m = NLPSentenceResponse{} }
func (m *NLPSentenceResponse) String() string { return proto.CompactTextString(m) }
func (*NLPSentenceResponse) ProtoMessage()    {}
func (*NLPSentenceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_04466eecc6514430, []int{3}
}

func (m *NLPSentenceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NLPSentenceResponse.Unmarshal(m, b)
}
func (m *NLPSentenceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NLPSentenceResponse.Marshal(b, m, deterministic)
}
func (m *NLPSentenceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NLPSentenceResponse.Merge(m, src)
}
func (m *NLPSentenceResponse) XXX_Size() int {
	return xxx_messageInfo_NLPSentenceResponse.Size(m)
}
func (m *NLPSentenceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NLPSentenceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NLPSentenceResponse proto.InternalMessageInfo

func (m *NLPSentenceResponse) GetFact() []byte {
	if m != nil {
		return m.Fact
	}
	return nil
}

func (m *NLPSentenceResponse) GetTokens() []string {
	if m != nil {
		return m.Tokens
	}
	return nil
}

func init() {
	proto.RegisterType((*NLPSentenceRequest)(nil), "proto.NLPSentenceRequest")
	proto.RegisterType((*TokenizedSentence)(nil), "proto.TokenizedSentence")
	proto.RegisterType((*AssistantMessage)(nil), "proto.AssistantMessage")
	proto.RegisterType((*NLPSentenceResponse)(nil), "proto.NLPSentenceResponse")
}

func init() { proto.RegisterFile("assistant.proto", fileDescriptor_04466eecc6514430) }

var fileDescriptor_04466eecc6514430 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4e, 0x83, 0x40,
	0x10, 0xc6, 0x43, 0xd1, 0x6a, 0x47, 0x13, 0x74, 0x4c, 0xcc, 0xca, 0x89, 0x70, 0xb1, 0x27, 0x0e,
	0xf5, 0x09, 0xaa, 0x17, 0x0f, 0x6a, 0x1a, 0xd4, 0x07, 0x40, 0x3a, 0x1a, 0x62, 0xba, 0x8b, 0xcc,
	0x54, 0x8d, 0x0f, 0xe0, 0x73, 0x9b, 0x9d, 0x2e, 0x24, 0x5a, 0x4f, 0xcc, 0xc7, 0xfc, 0xf9, 0x7e,
	0xdf, 0x42, 0x52, 0x31, 0x37, 0x2c, 0x95, 0x95, 0xa2, 0xed, 0x9c, 0x38, 0xdc, 0xd5, 0x4f, 0xfe,
	0x1d, 0x01, 0xde, 0xdd, 0x2c, 0xee, 0xc9, 0x0a, 0xd9, 0x9a, 0x4a, 0x7a, 0x5b, 0x13, 0x0b, 0x22,
	0xec, 0x48, 0xb3, 0x22, 0x13, 0x65, 0xd1, 0x74, 0x52, 0x6a, 0x8d, 0x06, 0xf6, 0x56, 0xc4, 0x5c,
	0xbd, 0x90, 0x19, 0xe9, 0xef, 0x5e, 0xe2, 0x25, 0x24, 0x6d, 0x47, 0xef, 0x8d, 0x5b, 0xf3, 0x95,
	0xb3, 0x42, 0x9f, 0x62, 0xe2, 0x2c, 0x9e, 0x1e, 0xcc, 0xcc, 0xc6, 0xac, 0x78, 0x70, 0xaf, 0x64,
	0x9b, 0x2f, 0x5a, 0x0e, 0x3e, 0x7f, 0x17, 0xf2, 0x73, 0x38, 0xde, 0x9a, 0xf2, 0x18, 0x1f, 0xae,
	0x5b, 0x9a, 0x28, 0x8b, 0x3d, 0x86, 0xaf, 0xf3, 0x02, 0x8e, 0xe6, 0x7d, 0x96, 0xdb, 0x00, 0x90,
	0xc2, 0x3e, 0x87, 0x9d, 0x80, 0x3c, 0xe8, 0x7c, 0x0e, 0x27, 0xbf, 0x02, 0x72, 0xeb, 0x2c, 0xeb,
	0xe9, 0xe7, 0xaa, 0x16, 0x1d, 0x3f, 0x2c, 0xb5, 0xc6, 0x53, 0x18, 0x8b, 0x67, 0x60, 0x33, 0x52,
	0xc3, 0xa0, 0x66, 0x8f, 0x30, 0x19, 0x2c, 0xf1, 0x1a, 0x92, 0xfe, 0xd8, 0xa2, 0x73, 0x35, 0x31,
	0xe3, 0x59, 0x88, 0xb9, 0xfd, 0x90, 0x69, 0xfa, 0x5f, 0x6b, 0x83, 0xf0, 0x34, 0xd6, 0xd6, 0xc5,
	0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0x98, 0x1d, 0x75, 0x9c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AssistantClient is the client API for Assistant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AssistantClient interface {
	SentenceProcess(ctx context.Context, in *NLPSentenceRequest, opts ...grpc.CallOption) (*NLPSentenceResponse, error)
}

type assistantClient struct {
	cc *grpc.ClientConn
}

func NewAssistantClient(cc *grpc.ClientConn) AssistantClient {
	return &assistantClient{cc}
}

func (c *assistantClient) SentenceProcess(ctx context.Context, in *NLPSentenceRequest, opts ...grpc.CallOption) (*NLPSentenceResponse, error) {
	out := new(NLPSentenceResponse)
	err := c.cc.Invoke(ctx, "/proto.Assistant/SentenceProcess", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssistantServer is the server API for Assistant service.
type AssistantServer interface {
	SentenceProcess(context.Context, *NLPSentenceRequest) (*NLPSentenceResponse, error)
}

// UnimplementedAssistantServer can be embedded to have forward compatible implementations.
type UnimplementedAssistantServer struct {
}

func (*UnimplementedAssistantServer) SentenceProcess(ctx context.Context, req *NLPSentenceRequest) (*NLPSentenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SentenceProcess not implemented")
}

func RegisterAssistantServer(s *grpc.Server, srv AssistantServer) {
	s.RegisterService(&_Assistant_serviceDesc, srv)
}

func _Assistant_SentenceProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NLPSentenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServer).SentenceProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Assistant/SentenceProcess",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServer).SentenceProcess(ctx, req.(*NLPSentenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Assistant_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Assistant",
	HandlerType: (*AssistantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SentenceProcess",
			Handler:    _Assistant_SentenceProcess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assistant.proto",
}
