version: "3.8"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.28
    container_name: myrtea-elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  pgsql:
    image: postgres:16-alpine
    container_name: myrtea-postgres
    ports:
      - "5432:5432"
    restart: always
  engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myrtea-engine
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - elastic
      - pgsql
    volumes:
      - "./config/engine-api.toml:/app/config/engine-api.toml"
      - "./config/services.toml:/app/config/services.toml"
