version: "3.8"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.0
    container_name: myrtea-elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  pgsql:
    image: postgres:11.0-alpine
    container_name: myrtea-postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "./resources/model.sql:/docker-entrypoint-initdb.d/1-init.sql"
  engine:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myrtea-engine
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - elastic
      - pgsql
    volumes:
      - "./config/engine-api.toml:/app/config/engine-api.toml"
