# Add your services here
#
# For plugins:
#
# Default plugin structure is:
# [[plugin]]
# name = "assistant"
# port = 9081
#
# Please note that the name will be used to find the plugin binaries "myrtea-NAME.plugin"
# Actually there are 3 types of plugins: assistant, baseline and standalone
# The assistant and baseline plugins are bidirectional and therefore cannot be used as name for standalone plugins.

#[[plugin]]
#name = "assistant"
#port = 9081

[[plugin]]
name = "flashdef"
port = 9082

# For connectors:
#
# key should be configured as the same security key in related connectors (ENGINE_API_KEY)
# components are the reload components that match with the related connector components
#
# Default connector structure is:
# [[connector]]
# name = "connector"
# url = "http://localhost:9091"
# key = "securitykey"
# components = ["test", "test"]