// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: baseline.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BaselineValueRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FactId              int64                  `protobuf:"varint,2,opt,name=fact_id,json=factId,proto3" json:"fact_id,omitempty"`
	SituationId         int64                  `protobuf:"varint,3,opt,name=situation_id,json=situationId,proto3" json:"situation_id,omitempty"`
	SituationInstanceId int64                  `protobuf:"varint,4,opt,name=situation_instance_id,json=situationInstanceId,proto3" json:"situation_instance_id,omitempty"`
	Time                string                 `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BaselineValueRequest) Reset() {
	*x = BaselineValueRequest{}
	mi := &file_baseline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaselineValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaselineValueRequest) ProtoMessage() {}

func (x *BaselineValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baseline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaselineValueRequest.ProtoReflect.Descriptor instead.
func (*BaselineValueRequest) Descriptor() ([]byte, []int) {
	return file_baseline_proto_rawDescGZIP(), []int{0}
}

func (x *BaselineValueRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaselineValueRequest) GetFactId() int64 {
	if x != nil {
		return x.FactId
	}
	return 0
}

func (x *BaselineValueRequest) GetSituationId() int64 {
	if x != nil {
		return x.SituationId
	}
	return 0
}

func (x *BaselineValueRequest) GetSituationInstanceId() int64 {
	if x != nil {
		return x.SituationInstanceId
	}
	return 0
}

func (x *BaselineValueRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type BuildBaselineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildBaselineRequest) Reset() {
	*x = BuildBaselineRequest{}
	mi := &file_baseline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildBaselineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildBaselineRequest) ProtoMessage() {}

func (x *BuildBaselineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baseline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildBaselineRequest.ProtoReflect.Descriptor instead.
func (*BuildBaselineRequest) Descriptor() ([]byte, []int) {
	return file_baseline_proto_rawDescGZIP(), []int{1}
}

func (x *BuildBaselineRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type BaselineValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          string                 `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	ValueLower    float64                `protobuf:"fixed64,3,opt,name=value_lower,json=valueLower,proto3" json:"value_lower,omitempty"`
	ValueUpper    float64                `protobuf:"fixed64,4,opt,name=value_upper,json=valueUpper,proto3" json:"value_upper,omitempty"`
	Avg           float64                `protobuf:"fixed64,5,opt,name=avg,proto3" json:"avg,omitempty"`
	Std           float64                `protobuf:"fixed64,6,opt,name=std,proto3" json:"std,omitempty"`
	Median        float64                `protobuf:"fixed64,7,opt,name=median,proto3" json:"median,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaselineValue) Reset() {
	*x = BaselineValue{}
	mi := &file_baseline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaselineValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaselineValue) ProtoMessage() {}

func (x *BaselineValue) ProtoReflect() protoreflect.Message {
	mi := &file_baseline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaselineValue.ProtoReflect.Descriptor instead.
func (*BaselineValue) Descriptor() ([]byte, []int) {
	return file_baseline_proto_rawDescGZIP(), []int{2}
}

func (x *BaselineValue) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *BaselineValue) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *BaselineValue) GetValueLower() float64 {
	if x != nil {
		return x.ValueLower
	}
	return 0
}

func (x *BaselineValue) GetValueUpper() float64 {
	if x != nil {
		return x.ValueUpper
	}
	return 0
}

func (x *BaselineValue) GetAvg() float64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *BaselineValue) GetStd() float64 {
	if x != nil {
		return x.Std
	}
	return 0
}

func (x *BaselineValue) GetMedian() float64 {
	if x != nil {
		return x.Median
	}
	return 0
}

type BaselineValues struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Values        map[string]*BaselineValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaselineValues) Reset() {
	*x = BaselineValues{}
	mi := &file_baseline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaselineValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaselineValues) ProtoMessage() {}

func (x *BaselineValues) ProtoReflect() protoreflect.Message {
	mi := &file_baseline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaselineValues.ProtoReflect.Descriptor instead.
func (*BaselineValues) Descriptor() ([]byte, []int) {
	return file_baseline_proto_rawDescGZIP(), []int{3}
}

func (x *BaselineValues) GetValues() map[string]*BaselineValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type MatrixProfileResultRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SituationId         int64                  `protobuf:"varint,1,opt,name=situation_id,json=situationId,proto3" json:"situation_id,omitempty"`
	SituationInstanceId int64                  `protobuf:"varint,2,opt,name=situation_instance_id,json=situationInstanceId,proto3" json:"situation_instance_id,omitempty"`
	Time                string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MatrixProfileResultRequest) Reset() {
	*x = MatrixProfileResultRequest{}
	mi := &file_baseline_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixProfileResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixProfileResultRequest) ProtoMessage() {}

func (x *MatrixProfileResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baseline_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixProfileResultRequest.ProtoReflect.Descriptor instead.
func (*MatrixProfileResultRequest) Descriptor() ([]byte, []int) {
	return file_baseline_proto_rawDescGZIP(), []int{4}
}

func (x *MatrixProfileResultRequest) GetSituationId() int64 {
	if x != nil {
		return x.SituationId
	}
	return 0
}

func (x *MatrixProfileResultRequest) GetSituationInstanceId() int64 {
	if x != nil {
		return x.SituationInstanceId
	}
	return 0
}

func (x *MatrixProfileResultRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type MatrixProfileResult struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Status                   string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MatchingScore            float64                `protobuf:"fixed64,2,opt,name=matching_score,json=matchingScore,proto3" json:"matching_score,omitempty"`
	MatchingScoreTheoretical float64                `protobuf:"fixed64,3,opt,name=matching_score_theoretical,json=matchingScoreTheoretical,proto3" json:"matching_score_theoretical,omitempty"`
	BestMatchTime            string                 `protobuf:"bytes,4,opt,name=best_match_time,json=bestMatchTime,proto3" json:"best_match_time,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MatrixProfileResult) Reset() {
	*x = MatrixProfileResult{}
	mi := &file_baseline_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixProfileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixProfileResult) ProtoMessage() {}

func (x *MatrixProfileResult) ProtoReflect() protoreflect.Message {
	mi := &file_baseline_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixProfileResult.ProtoReflect.Descriptor instead.
func (*MatrixProfileResult) Descriptor() ([]byte, []int) {
	return file_baseline_proto_rawDescGZIP(), []int{5}
}

func (x *MatrixProfileResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MatrixProfileResult) GetMatchingScore() float64 {
	if x != nil {
		return x.MatchingScore
	}
	return 0
}

func (x *MatrixProfileResult) GetMatchingScoreTheoretical() float64 {
	if x != nil {
		return x.MatchingScoreTheoretical
	}
	return 0
}

func (x *MatrixProfileResult) GetBestMatchTime() string {
	if x != nil {
		return x.BestMatchTime
	}
	return ""
}

type MatrixProfileResults struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Values        map[string]*MatrixProfileResult `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatrixProfileResults) Reset() {
	*x = MatrixProfileResults{}
	mi := &file_baseline_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixProfileResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixProfileResults) ProtoMessage() {}

func (x *MatrixProfileResults) ProtoReflect() protoreflect.Message {
	mi := &file_baseline_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixProfileResults.ProtoReflect.Descriptor instead.
func (*MatrixProfileResults) Descriptor() ([]byte, []int) {
	return file_baseline_proto_rawDescGZIP(), []int{6}
}

func (x *MatrixProfileResults) GetValues() map[string]*MatrixProfileResult {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_baseline_proto protoreflect.FileDescriptor

const file_baseline_proto_rawDesc = "" +
	"\n" +
	"\x0ebaseline.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\xaa\x01\n" +
	"\x14BaselineValueRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\afact_id\x18\x02 \x01(\x03R\x06factId\x12!\n" +
	"\fsituation_id\x18\x03 \x01(\x03R\vsituationId\x122\n" +
	"\x15situation_instance_id\x18\x04 \x01(\x03R\x13situationInstanceId\x12\x12\n" +
	"\x04time\x18\x05 \x01(\tR\x04time\"&\n" +
	"\x14BuildBaselineRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xb7\x01\n" +
	"\rBaselineValue\x12\x12\n" +
	"\x04time\x18\x01 \x01(\tR\x04time\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12\x1f\n" +
	"\vvalue_lower\x18\x03 \x01(\x01R\n" +
	"valueLower\x12\x1f\n" +
	"\vvalue_upper\x18\x04 \x01(\x01R\n" +
	"valueUpper\x12\x10\n" +
	"\x03avg\x18\x05 \x01(\x01R\x03avg\x12\x10\n" +
	"\x03std\x18\x06 \x01(\x01R\x03std\x12\x16\n" +
	"\x06median\x18\a \x01(\x01R\x06median\"\x9c\x01\n" +
	"\x0eBaselineValues\x129\n" +
	"\x06values\x18\x01 \x03(\v2!.proto.BaselineValues.ValuesEntryR\x06values\x1aO\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.proto.BaselineValueR\x05value:\x028\x01\"\x87\x01\n" +
	"\x1aMatrixProfileResultRequest\x12!\n" +
	"\fsituation_id\x18\x01 \x01(\x03R\vsituationId\x122\n" +
	"\x15situation_instance_id\x18\x02 \x01(\x03R\x13situationInstanceId\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\"\xba\x01\n" +
	"\x13MatrixProfileResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0ematching_score\x18\x02 \x01(\x01R\rmatchingScore\x12<\n" +
	"\x1amatching_score_theoretical\x18\x03 \x01(\x01R\x18matchingScoreTheoretical\x12&\n" +
	"\x0fbest_match_time\x18\x04 \x01(\tR\rbestMatchTime\"\xae\x01\n" +
	"\x14MatrixProfileResults\x12?\n" +
	"\x06values\x18\x01 \x03(\v2'.proto.MatrixProfileResults.ValuesEntryR\x06values\x1aU\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.proto.MatrixProfileResultR\x05value:\x028\x012\x80\x02\n" +
	"\bBaseline\x12I\n" +
	"\x11GetBaselineValues\x12\x1b.proto.BaselineValueRequest\x1a\x15.proto.BaselineValues\"\x00\x12L\n" +
	"\x13BuildBaselineValues\x12\x1b.proto.BuildBaselineRequest\x1a\x16.google.protobuf.Empty\"\x00\x12[\n" +
	"\x17GetMatrixProfileResults\x12!.proto.MatrixProfileResultRequest\x1a\x1b.proto.MatrixProfileResults\"\x00BCZAgithub.com/myrteametrics/myrtea-engine-api/plugins/baseline/protob\x06proto3"

var (
	file_baseline_proto_rawDescOnce sync.Once
	file_baseline_proto_rawDescData []byte
)

func file_baseline_proto_rawDescGZIP() []byte {
	file_baseline_proto_rawDescOnce.Do(func() {
		file_baseline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baseline_proto_rawDesc), len(file_baseline_proto_rawDesc)))
	})
	return file_baseline_proto_rawDescData
}

var file_baseline_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_baseline_proto_goTypes = []any{
	(*BaselineValueRequest)(nil),       // 0: proto.BaselineValueRequest
	(*BuildBaselineRequest)(nil),       // 1: proto.BuildBaselineRequest
	(*BaselineValue)(nil),              // 2: proto.BaselineValue
	(*BaselineValues)(nil),             // 3: proto.BaselineValues
	(*MatrixProfileResultRequest)(nil), // 4: proto.MatrixProfileResultRequest
	(*MatrixProfileResult)(nil),        // 5: proto.MatrixProfileResult
	(*MatrixProfileResults)(nil),       // 6: proto.MatrixProfileResults
	nil,                                // 7: proto.BaselineValues.ValuesEntry
	nil,                                // 8: proto.MatrixProfileResults.ValuesEntry
	(*emptypb.Empty)(nil),              // 9: google.protobuf.Empty
}
var file_baseline_proto_depIdxs = []int32{
	7, // 0: proto.BaselineValues.values:type_name -> proto.BaselineValues.ValuesEntry
	8, // 1: proto.MatrixProfileResults.values:type_name -> proto.MatrixProfileResults.ValuesEntry
	2, // 2: proto.BaselineValues.ValuesEntry.value:type_name -> proto.BaselineValue
	5, // 3: proto.MatrixProfileResults.ValuesEntry.value:type_name -> proto.MatrixProfileResult
	0, // 4: proto.Baseline.GetBaselineValues:input_type -> proto.BaselineValueRequest
	1, // 5: proto.Baseline.BuildBaselineValues:input_type -> proto.BuildBaselineRequest
	4, // 6: proto.Baseline.GetMatrixProfileResults:input_type -> proto.MatrixProfileResultRequest
	3, // 7: proto.Baseline.GetBaselineValues:output_type -> proto.BaselineValues
	9, // 8: proto.Baseline.BuildBaselineValues:output_type -> google.protobuf.Empty
	6, // 9: proto.Baseline.GetMatrixProfileResults:output_type -> proto.MatrixProfileResults
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_baseline_proto_init() }
func file_baseline_proto_init() {
	if File_baseline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baseline_proto_rawDesc), len(file_baseline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baseline_proto_goTypes,
		DependencyIndexes: file_baseline_proto_depIdxs,
		MessageInfos:      file_baseline_proto_msgTypes,
	}.Build()
	File_baseline_proto = out.File
	file_baseline_proto_goTypes = nil
	file_baseline_proto_depIdxs = nil
}
