// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: baseline.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatrixProfileResultRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SituationId         int64                  `protobuf:"varint,1,opt,name=situation_id,json=situationId,proto3" json:"situation_id,omitempty"`
	SituationInstanceId int64                  `protobuf:"varint,2,opt,name=situation_instance_id,json=situationInstanceId,proto3" json:"situation_instance_id,omitempty"`
	Time                string                 `protobuf:"bytes,3,opt,name=time,proto3" json:"time,omitempty"`
	// Expression facts evaluated for the current tick, keyed by name. A definition whose
	// value_type is "fact_expression" reads its current point from here instead of from
	// situation_history_v5, since that row is not written until after this call returns.
	ExpressionFacts map[string]float64 `protobuf:"bytes,4,rep,name=expression_facts,json=expressionFacts,proto3" json:"expression_facts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatrixProfileResultRequest) Reset() {
	*x = MatrixProfileResultRequest{}
	mi := &file_baseline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixProfileResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixProfileResultRequest) ProtoMessage() {}

func (x *MatrixProfileResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_baseline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixProfileResultRequest.ProtoReflect.Descriptor instead.
func (*MatrixProfileResultRequest) Descriptor() ([]byte, []int) {
	return file_baseline_proto_rawDescGZIP(), []int{0}
}

func (x *MatrixProfileResultRequest) GetSituationId() int64 {
	if x != nil {
		return x.SituationId
	}
	return 0
}

func (x *MatrixProfileResultRequest) GetSituationInstanceId() int64 {
	if x != nil {
		return x.SituationInstanceId
	}
	return 0
}

func (x *MatrixProfileResultRequest) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *MatrixProfileResultRequest) GetExpressionFacts() map[string]float64 {
	if x != nil {
		return x.ExpressionFacts
	}
	return nil
}

type MatrixProfileResult struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Status                   string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MatchingScore            float64                `protobuf:"fixed64,2,opt,name=matching_score,json=matchingScore,proto3" json:"matching_score,omitempty"`
	MatchingScoreTheoretical float64                `protobuf:"fixed64,3,opt,name=matching_score_theoretical,json=matchingScoreTheoretical,proto3" json:"matching_score_theoretical,omitempty"`
	BestMatchTime            string                 `protobuf:"bytes,4,opt,name=best_match_time,json=bestMatchTime,proto3" json:"best_match_time,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MatrixProfileResult) Reset() {
	*x = MatrixProfileResult{}
	mi := &file_baseline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixProfileResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixProfileResult) ProtoMessage() {}

func (x *MatrixProfileResult) ProtoReflect() protoreflect.Message {
	mi := &file_baseline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixProfileResult.ProtoReflect.Descriptor instead.
func (*MatrixProfileResult) Descriptor() ([]byte, []int) {
	return file_baseline_proto_rawDescGZIP(), []int{1}
}

func (x *MatrixProfileResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MatrixProfileResult) GetMatchingScore() float64 {
	if x != nil {
		return x.MatchingScore
	}
	return 0
}

func (x *MatrixProfileResult) GetMatchingScoreTheoretical() float64 {
	if x != nil {
		return x.MatchingScoreTheoretical
	}
	return 0
}

func (x *MatrixProfileResult) GetBestMatchTime() string {
	if x != nil {
		return x.BestMatchTime
	}
	return ""
}

type MatrixProfileResults struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Values        map[string]*MatrixProfileResult `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatrixProfileResults) Reset() {
	*x = MatrixProfileResults{}
	mi := &file_baseline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatrixProfileResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatrixProfileResults) ProtoMessage() {}

func (x *MatrixProfileResults) ProtoReflect() protoreflect.Message {
	mi := &file_baseline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatrixProfileResults.ProtoReflect.Descriptor instead.
func (*MatrixProfileResults) Descriptor() ([]byte, []int) {
	return file_baseline_proto_rawDescGZIP(), []int{2}
}

func (x *MatrixProfileResults) GetValues() map[string]*MatrixProfileResult {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_baseline_proto protoreflect.FileDescriptor

const file_baseline_proto_rawDesc = "" +
	"\n" +
	"\x0ebaseline.proto\x12\x05proto\"\xae\x02\n" +
	"\x1aMatrixProfileResultRequest\x12!\n" +
	"\fsituation_id\x18\x01 \x01(\x03R\vsituationId\x122\n" +
	"\x15situation_instance_id\x18\x02 \x01(\x03R\x13situationInstanceId\x12\x12\n" +
	"\x04time\x18\x03 \x01(\tR\x04time\x12a\n" +
	"\x10expression_facts\x18\x04 \x03(\v26.proto.MatrixProfileResultRequest.ExpressionFactsEntryR\x0fexpressionFacts\x1aB\n" +
	"\x14ExpressionFactsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xba\x01\n" +
	"\x13MatrixProfileResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0ematching_score\x18\x02 \x01(\x01R\rmatchingScore\x12<\n" +
	"\x1amatching_score_theoretical\x18\x03 \x01(\x01R\x18matchingScoreTheoretical\x12&\n" +
	"\x0fbest_match_time\x18\x04 \x01(\tR\rbestMatchTime\"\xae\x01\n" +
	"\x14MatrixProfileResults\x12?\n" +
	"\x06values\x18\x01 \x03(\v2'.proto.MatrixProfileResults.ValuesEntryR\x06values\x1aU\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.proto.MatrixProfileResultR\x05value:\x028\x012g\n" +
	"\bBaseline\x12[\n" +
	"\x17GetMatrixProfileResults\x12!.proto.MatrixProfileResultRequest\x1a\x1b.proto.MatrixProfileResults\"\x00BCZAgithub.com/myrteametrics/myrtea-engine-api/plugins/baseline/protob\x06proto3"

var (
	file_baseline_proto_rawDescOnce sync.Once
	file_baseline_proto_rawDescData []byte
)

func file_baseline_proto_rawDescGZIP() []byte {
	file_baseline_proto_rawDescOnce.Do(func() {
		file_baseline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_baseline_proto_rawDesc), len(file_baseline_proto_rawDesc)))
	})
	return file_baseline_proto_rawDescData
}

var file_baseline_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_baseline_proto_goTypes = []any{
	(*MatrixProfileResultRequest)(nil), // 0: proto.MatrixProfileResultRequest
	(*MatrixProfileResult)(nil),        // 1: proto.MatrixProfileResult
	(*MatrixProfileResults)(nil),       // 2: proto.MatrixProfileResults
	nil,                                // 3: proto.MatrixProfileResultRequest.ExpressionFactsEntry
	nil,                                // 4: proto.MatrixProfileResults.ValuesEntry
}
var file_baseline_proto_depIdxs = []int32{
	3, // 0: proto.MatrixProfileResultRequest.expression_facts:type_name -> proto.MatrixProfileResultRequest.ExpressionFactsEntry
	4, // 1: proto.MatrixProfileResults.values:type_name -> proto.MatrixProfileResults.ValuesEntry
	1, // 2: proto.MatrixProfileResults.ValuesEntry.value:type_name -> proto.MatrixProfileResult
	0, // 3: proto.Baseline.GetMatrixProfileResults:input_type -> proto.MatrixProfileResultRequest
	2, // 4: proto.Baseline.GetMatrixProfileResults:output_type -> proto.MatrixProfileResults
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_baseline_proto_init() }
func file_baseline_proto_init() {
	if File_baseline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_baseline_proto_rawDesc), len(file_baseline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_baseline_proto_goTypes,
		DependencyIndexes: file_baseline_proto_depIdxs,
		MessageInfos:      file_baseline_proto_msgTypes,
	}.Build()
	File_baseline_proto = out.File
	file_baseline_proto_goTypes = nil
	file_baseline_proto_depIdxs = nil
}
