// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: baseline.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Baseline_GetMatrixProfileResults_FullMethodName = "/proto.Baseline/GetMatrixProfileResults"
)

// BaselineClient is the client API for Baseline service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BaselineClient interface {
	GetMatrixProfileResults(ctx context.Context, in *MatrixProfileResultRequest, opts ...grpc.CallOption) (*MatrixProfileResults, error)
}

type baselineClient struct {
	cc grpc.ClientConnInterface
}

func NewBaselineClient(cc grpc.ClientConnInterface) BaselineClient {
	return &baselineClient{cc}
}

func (c *baselineClient) GetMatrixProfileResults(ctx context.Context, in *MatrixProfileResultRequest, opts ...grpc.CallOption) (*MatrixProfileResults, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatrixProfileResults)
	err := c.cc.Invoke(ctx, Baseline_GetMatrixProfileResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaselineServer is the server API for Baseline service.
// All implementations must embed UnimplementedBaselineServer
// for forward compatibility.
type BaselineServer interface {
	GetMatrixProfileResults(context.Context, *MatrixProfileResultRequest) (*MatrixProfileResults, error)
	mustEmbedUnimplementedBaselineServer()
}

// UnimplementedBaselineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaselineServer struct{}

func (UnimplementedBaselineServer) GetMatrixProfileResults(context.Context, *MatrixProfileResultRequest) (*MatrixProfileResults, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMatrixProfileResults not implemented")
}
func (UnimplementedBaselineServer) mustEmbedUnimplementedBaselineServer() {}
func (UnimplementedBaselineServer) testEmbeddedByValue()                  {}

// UnsafeBaselineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaselineServer will
// result in compilation errors.
type UnsafeBaselineServer interface {
	mustEmbedUnimplementedBaselineServer()
}

func RegisterBaselineServer(s grpc.ServiceRegistrar, srv BaselineServer) {
	// If the following call panics, it indicates UnimplementedBaselineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Baseline_ServiceDesc, srv)
}

func _Baseline_GetMatrixProfileResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatrixProfileResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaselineServer).GetMatrixProfileResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Baseline_GetMatrixProfileResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaselineServer).GetMatrixProfileResults(ctx, req.(*MatrixProfileResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Baseline_ServiceDesc is the grpc.ServiceDesc for Baseline service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Baseline_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Baseline",
	HandlerType: (*BaselineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMatrixProfileResults",
			Handler:    _Baseline_GetMatrixProfileResults_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baseline.proto",
}
