// Code generated by protoc-gen-go. DO NOT EDIT.
// source: baseline.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BaselineValueRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FactId               int64    `protobuf:"varint,2,opt,name=fact_id,json=factId,proto3" json:"fact_id,omitempty"`
	SituationId          int64    `protobuf:"varint,3,opt,name=situation_id,json=situationId,proto3" json:"situation_id,omitempty"`
	SituationInstanceId  int64    `protobuf:"varint,4,opt,name=situation_instance_id,json=situationInstanceId,proto3" json:"situation_instance_id,omitempty"`
	Time                 string   `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaselineValueRequest) Reset()         { *m = BaselineValueRequest{} }
func (m *BaselineValueRequest) String() string { return proto.CompactTextString(m) }
func (*BaselineValueRequest) ProtoMessage()    {}
func (*BaselineValueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec690dc20fe6fed, []int{0}
}

func (m *BaselineValueRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaselineValueRequest.Unmarshal(m, b)
}
func (m *BaselineValueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaselineValueRequest.Marshal(b, m, deterministic)
}
func (m *BaselineValueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaselineValueRequest.Merge(m, src)
}
func (m *BaselineValueRequest) XXX_Size() int {
	return xxx_messageInfo_BaselineValueRequest.Size(m)
}
func (m *BaselineValueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BaselineValueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BaselineValueRequest proto.InternalMessageInfo

func (m *BaselineValueRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BaselineValueRequest) GetFactId() int64 {
	if m != nil {
		return m.FactId
	}
	return 0
}

func (m *BaselineValueRequest) GetSituationId() int64 {
	if m != nil {
		return m.SituationId
	}
	return 0
}

func (m *BaselineValueRequest) GetSituationInstanceId() int64 {
	if m != nil {
		return m.SituationInstanceId
	}
	return 0
}

func (m *BaselineValueRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type BaselineValue struct {
	Time                 string   `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Value                float64  `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	ValueLower           float64  `protobuf:"fixed64,3,opt,name=value_lower,json=valueLower,proto3" json:"value_lower,omitempty"`
	ValueUpper           float64  `protobuf:"fixed64,4,opt,name=value_upper,json=valueUpper,proto3" json:"value_upper,omitempty"`
	Avg                  float64  `protobuf:"fixed64,5,opt,name=avg,proto3" json:"avg,omitempty"`
	Std                  float64  `protobuf:"fixed64,6,opt,name=std,proto3" json:"std,omitempty"`
	Median               float64  `protobuf:"fixed64,7,opt,name=median,proto3" json:"median,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaselineValue) Reset()         { *m = BaselineValue{} }
func (m *BaselineValue) String() string { return proto.CompactTextString(m) }
func (*BaselineValue) ProtoMessage()    {}
func (*BaselineValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec690dc20fe6fed, []int{1}
}

func (m *BaselineValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaselineValue.Unmarshal(m, b)
}
func (m *BaselineValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaselineValue.Marshal(b, m, deterministic)
}
func (m *BaselineValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaselineValue.Merge(m, src)
}
func (m *BaselineValue) XXX_Size() int {
	return xxx_messageInfo_BaselineValue.Size(m)
}
func (m *BaselineValue) XXX_DiscardUnknown() {
	xxx_messageInfo_BaselineValue.DiscardUnknown(m)
}

var xxx_messageInfo_BaselineValue proto.InternalMessageInfo

func (m *BaselineValue) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *BaselineValue) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *BaselineValue) GetValueLower() float64 {
	if m != nil {
		return m.ValueLower
	}
	return 0
}

func (m *BaselineValue) GetValueUpper() float64 {
	if m != nil {
		return m.ValueUpper
	}
	return 0
}

func (m *BaselineValue) GetAvg() float64 {
	if m != nil {
		return m.Avg
	}
	return 0
}

func (m *BaselineValue) GetStd() float64 {
	if m != nil {
		return m.Std
	}
	return 0
}

func (m *BaselineValue) GetMedian() float64 {
	if m != nil {
		return m.Median
	}
	return 0
}

type BaselineValues struct {
	Values               map[string]*BaselineValue `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *BaselineValues) Reset()         { *m = BaselineValues{} }
func (m *BaselineValues) String() string { return proto.CompactTextString(m) }
func (*BaselineValues) ProtoMessage()    {}
func (*BaselineValues) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ec690dc20fe6fed, []int{2}
}

func (m *BaselineValues) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaselineValues.Unmarshal(m, b)
}
func (m *BaselineValues) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaselineValues.Marshal(b, m, deterministic)
}
func (m *BaselineValues) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaselineValues.Merge(m, src)
}
func (m *BaselineValues) XXX_Size() int {
	return xxx_messageInfo_BaselineValues.Size(m)
}
func (m *BaselineValues) XXX_DiscardUnknown() {
	xxx_messageInfo_BaselineValues.DiscardUnknown(m)
}

var xxx_messageInfo_BaselineValues proto.InternalMessageInfo

func (m *BaselineValues) GetValues() map[string]*BaselineValue {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*BaselineValueRequest)(nil), "proto.BaselineValueRequest")
	proto.RegisterType((*BaselineValue)(nil), "proto.BaselineValue")
	proto.RegisterType((*BaselineValues)(nil), "proto.BaselineValues")
	proto.RegisterMapType((map[string]*BaselineValue)(nil), "proto.BaselineValues.ValuesEntry")
}

func init() { proto.RegisterFile("baseline.proto", fileDescriptor_8ec690dc20fe6fed) }

var fileDescriptor_8ec690dc20fe6fed = []byte{
	// 348 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x4f, 0xf2, 0x40,
	0x10, 0xc6, 0xb3, 0x2d, 0x94, 0xf7, 0x9d, 0x2a, 0xd1, 0x11, 0xb4, 0xc1, 0x83, 0xc0, 0x89, 0x78,
	0xe0, 0x50, 0x2f, 0xea, 0xd1, 0xc4, 0x10, 0x12, 0x13, 0x93, 0x35, 0x7a, 0x25, 0x0b, 0xbb, 0x9a,
	0x8d, 0xd0, 0x62, 0x77, 0x8b, 0xe1, 0xbb, 0xf8, 0x09, 0xfc, 0x02, 0x7e, 0x3d, 0xb3, 0xd3, 0xf2,
	0xcf, 0x70, 0x9a, 0x99, 0xdf, 0xf3, 0x74, 0xf2, 0x64, 0xba, 0x50, 0x1f, 0x0b, 0xa3, 0xa6, 0x3a,
	0x51, 0xfd, 0x79, 0x96, 0xda, 0x14, 0xab, 0x54, 0xba, 0xdf, 0x0c, 0x1a, 0x77, 0xa5, 0xf2, 0x22,
	0xa6, 0xb9, 0xe2, 0xea, 0x23, 0x57, 0xc6, 0x62, 0x1d, 0x3c, 0x2d, 0x23, 0xd6, 0x66, 0x3d, 0x9f,
	0x7b, 0x5a, 0xe2, 0x19, 0xd4, 0x5e, 0xc5, 0xc4, 0x8e, 0xb4, 0x8c, 0x3c, 0x82, 0x81, 0x1b, 0x87,
	0x12, 0x3b, 0x70, 0x60, 0xb4, 0xcd, 0x85, 0xd5, 0x69, 0xe2, 0x54, 0x9f, 0xd4, 0x70, 0xcd, 0x86,
	0x12, 0x63, 0x68, 0x6e, 0x59, 0x12, 0x63, 0x45, 0x32, 0x51, 0xce, 0x5b, 0x21, 0xef, 0xc9, 0xc6,
	0x5b, 0x6a, 0x43, 0x89, 0x08, 0x15, 0xab, 0x67, 0x2a, 0xaa, 0xb6, 0x59, 0xef, 0x3f, 0xa7, 0xbe,
	0xfb, 0xc3, 0xe0, 0x70, 0x27, 0xec, 0xda, 0xc5, 0x36, 0x2e, 0x6c, 0x40, 0x75, 0xe1, 0x44, 0xca,
	0xc9, 0x78, 0x31, 0xe0, 0x05, 0x84, 0xd4, 0x8c, 0xa6, 0xe9, 0xa7, 0xca, 0x28, 0x25, 0xe3, 0x40,
	0xe8, 0xc1, 0x91, 0x8d, 0x21, 0x9f, 0xcf, 0x55, 0x46, 0xd1, 0x56, 0x86, 0x67, 0x47, 0xf0, 0x08,
	0x7c, 0xb1, 0x78, 0xa3, 0x40, 0x8c, 0xbb, 0xd6, 0x11, 0x63, 0x65, 0x14, 0x14, 0xc4, 0x58, 0x89,
	0xa7, 0x10, 0xcc, 0x94, 0xd4, 0x22, 0x89, 0x6a, 0x04, 0xcb, 0xa9, 0xfb, 0xc5, 0xa0, 0xbe, 0x93,
	0xdc, 0xe0, 0x0d, 0x04, 0xb4, 0xdc, 0x44, 0xac, 0xed, 0xf7, 0xc2, 0xb8, 0x53, 0xfc, 0x98, 0xfe,
	0xae, 0xad, 0x5f, 0x94, 0xfb, 0xc4, 0x66, 0x4b, 0x5e, 0x7e, 0xd0, 0x7a, 0x84, 0x70, 0x0b, 0xbb,
	0x18, 0xef, 0x6a, 0x59, 0xde, 0xc0, 0xb5, 0x78, 0xb9, 0x7d, 0x82, 0x30, 0x6e, 0xec, 0x5b, 0x5d,
	0x1e, 0xe6, 0xd6, 0xbb, 0x66, 0xf1, 0x13, 0xfc, 0x5b, 0x69, 0x38, 0x80, 0xe3, 0x81, 0xb2, 0x7f,
	0xc2, 0x9e, 0xef, 0xdd, 0x50, 0x3c, 0x95, 0x56, 0x73, 0x6f, 0xf2, 0x71, 0x40, 0xf4, 0xea, 0x37,
	0x00, 0x00, 0xff, 0xff, 0x49, 0x7f, 0xa6, 0x74, 0x7a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BaselineClient is the client API for Baseline service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BaselineClient interface {
	// rpc GetBaselineValue(BaselineValueRequest) returns (BaselineValue);
	GetBaselineValues(ctx context.Context, in *BaselineValueRequest, opts ...grpc.CallOption) (*BaselineValues, error)
}

type baselineClient struct {
	cc *grpc.ClientConn
}

func NewBaselineClient(cc *grpc.ClientConn) BaselineClient {
	return &baselineClient{cc}
}

func (c *baselineClient) GetBaselineValues(ctx context.Context, in *BaselineValueRequest, opts ...grpc.CallOption) (*BaselineValues, error) {
	out := new(BaselineValues)
	err := c.cc.Invoke(ctx, "/proto.Baseline/GetBaselineValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaselineServer is the server API for Baseline service.
type BaselineServer interface {
	// rpc GetBaselineValue(BaselineValueRequest) returns (BaselineValue);
	GetBaselineValues(context.Context, *BaselineValueRequest) (*BaselineValues, error)
}

// UnimplementedBaselineServer can be embedded to have forward compatible implementations.
type UnimplementedBaselineServer struct {
}

func (*UnimplementedBaselineServer) GetBaselineValues(ctx context.Context, req *BaselineValueRequest) (*BaselineValues, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBaselineValues not implemented")
}

func RegisterBaselineServer(s *grpc.Server, srv BaselineServer) {
	s.RegisterService(&_Baseline_serviceDesc, srv)
}

func _Baseline_GetBaselineValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BaselineValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaselineServer).GetBaselineValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Baseline/GetBaselineValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaselineServer).GetBaselineValues(ctx, req.(*BaselineValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Baseline_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Baseline",
	HandlerType: (*BaselineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBaselineValues",
			Handler:    _Baseline_GetBaselineValues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "baseline.proto",
}
