# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Initialize Swag
      run: |
        go install github.com/swaggo/swag/cmd/swag@latest
        swag init --parseDependency --generalInfo main.go

    - name: Build
      run: go build -v ./...

    - name: Coverage
      uses: gwatts/go-coverage-action@v1
      with:
        add-comment: true
        test-args: '["-short"]'
