# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Initialize Swag
      run: |
        go install github.com/swaggo/swag/cmd/swag@latest
        swag init --parseDependency --generalInfo main.go

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -short -v ./...

    - name: Coverage
      uses: gwatts/go-coverage-action@v2
    #  if: github.ref == 'refs/heads/master'
    #  continue-on-error: true
      with:
        add-comment: true
        test-args: '["-short"]' # find solution for elastic & sql tests
